safe: false
pygments: true
lsi: false
permalink: /:categories/:title
url: https://ryanseys.com
markdown: maruku
port: 4000
encoding: UTF-8
future: false
excerpt_separator: "<!-- end_excerpt -->"
exclude:
- README.md
- params.json
- Gemfile
- Gemfile.lock
- vendor
- config.ru
- Procfile
- Dockerfile

assets:
  sources:
    - _assets/css
    - _assets/js
  debug: true
